import { useEffect, useMemo, useState } from "react";
import { getAffiliateDashboard } from "../api/affiliates.js";

const currency = (value) => new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(Number(value || 0));

const PartnerConversions = () => {
  const [data, setData] = useState({ referrals: [] });
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("all");
  const [loading, setLoading] = useState(true);
  useEffect(() => { getAffiliateDashboard().then(setData).finally(() => setLoading(false)); }, []);
  const rows = useMemo(() => (data.referrals || []).filter((item) => `${item.businessName} ${item.ownerName} ${item.industry}`.toLowerCase().includes(query.toLowerCase())).filter((item) => status === "all" || (status === "converted" ? item.converted : !item.converted)), [data.referrals, query, status]);
  return <section className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-[0.3em] text-emerald-300">Live conversions</p><h1 className="mt-2 text-3xl font-semibold text-white">Referred businesses</h1><p className="mt-2 text-sm text-slate-400">Track registration, subscription state, and commission outcome.</p></div><div className="flex flex-col gap-3 rounded-2xl border border-white/10 bg-slate-900 p-4 sm:flex-row"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search business or owner" className="flex-1 rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-sm text-white outline-none focus:border-emerald-400" /><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-sm text-white"><option value="all">All statuses</option><option value="converted">Converted</option><option value="pending">Not converted</option></select></div><div className="overflow-x-auto rounded-3xl border border-white/10 bg-slate-900">{loading ? <p className="p-8 text-sm text-slate-400">Loading conversions...</p> : rows.length === 0 ? <p className="p-8 text-sm text-slate-400">No matching referrals found.</p> : <table className="min-w-full text-left text-sm"><thead className="border-b border-white/10 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Business</th><th className="px-5 py-4">Owner</th><th className="px-5 py-4">Plan</th><th className="px-5 py-4">Conversion</th><th className="px-5 py-4">Commission</th><th className="px-5 py-4">Joined</th></tr></thead><tbody className="divide-y divide-white/10">{rows.map((item) => <tr key={item.businessId} className="text-slate-200"><td className="px-5 py-4 font-semibold text-white">{item.businessName}<p className="text-xs text-slate-500">{item.industry}</p></td><td className="px-5 py-4">{item.ownerName}<p className="text-xs text-slate-500">{item.ownerEmail}</p></td><td className="px-5 py-4"><span className="rounded-full bg-slate-500/15 px-2.5 py-1 text-xs">{item.isPro ? "Pro" : "Free"}</span></td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs ${item.converted ? "bg-emerald-500/15 text-emerald-300" : "bg-amber-500/15 text-amber-300"}`}>{item.converted ? "Converted" : "Registered"}</span></td><td className="px-5 py-4 font-semibold text-emerald-300">{currency(item.commissionEarned)}</td><td className="px-5 py-4 text-slate-400">{item.referredAt}</td></tr>)}</tbody></table>}</div></section>;
};
export default PartnerConversions;
